packages:
  - "packages/*"

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  typescript: ^5.9.0
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  "@mui/material": ^7.3.8
  "@emotion/react": ^11.14.0
  "@emotion/styled": ^11.14.1
  tss-react: ^4.9.20
